// import React from 'react'
// import styles from './styles.module.css'

export { usePageVisible } from './usePageVisible'
export { useWindowSize } from './useWindowSize'
export { useDebounce } from './useDebounce'
export { usePrevious } from './usePrevious'
export { useHover } from './useHover'
export { useScrolling } from './useScrolling'
export { useBeforeUnload } from './useBeforeUnload'
export { useThrottle } from './useThrottle'
export { useLocalStorage } from './useLocalStorage'
export { useEqualObject } from './useEqualObject'
export { useCookie } from './useCookie'
export { useGeolocation } from './useGeolocation'
export { useIsFirstRender } from './useIsFirstRender'
export { useConnection } from './useConnection'
export { useBatteryInfo } from './useBatteryInfo'
export { useCopyToClipboard } from './useCopyToClipboard'
export { useMedia } from './useMedia'
export { useClickOutside } from './useClickOutside'
export { useColorScheme } from './useColorScheme'
export { useFullScreen } from './useFullScreen'
